name: Destroy Terraform

on:
  workflow_dispatch:

env:
  BACKEND_BUCKET:  "site-pucminas-123456"
  BACKEND_PREFIX:  "state/terraform.tfstate"
  TF_VAR_aws_region:     "us-east-1"
  AWS_ACCESS_KEY_ID   : ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY : ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_aws_public_key : ${{ secrets.AWS_PUBLIC_KEY }}
  ENV   : prod


jobs:
  Destroy:
    name: Destroy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infrastructure
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: |
          terraform init -backend-config="bucket=$BACKEND_BUCKET" -backend-config="key=$BACKEND_PREFIX" -backend-config="region=$TF_VAR_aws_region"
          terraform workspace new $ENV || terraform workspace select $ENV

      - name: Terraform Destroy
        run: |
          terraform destroy -auto-approve